encoder:
  model_path: "sentence-transformers/all-MiniLM-l6-v2"

  model_kwargs: 
    device: "cuda"

  encode_kwargs:
    normalize_embeddings: False

retriever:
  splitting:
    chunk_size: 256
    chunk_overlap: 16
  num_docs: 4

generator:
  llm_path: "models/llama-2-7b.Q5_K_M.gguf"
  context_length: 2048
  temperature: 0.7
  max_tokens: 256
  gpu_layers: 50
  model_kwargs: {}

web:
  serp_api_key: "<YOUR_API_KEY>"